name: Setup Rust
description: Setup Rust environment for CI workflows
inputs:
  key:
    description: A disambiguator namespace for the cache.
    default: cargo
  key-suffix:
    description: An additional suffix to append to the cache key.
    default: ""
  readonly-cache:
    description: Whether to update the cache after a job completes or not.
    default: "false"
runs:
  using: "composite"
  steps:
    - if: ${{ inputs.readonly-cache != 'true' }}
      name: Cache
      id: cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-${{ inputs.key }}-${{ hashFiles('**/Cargo.lock') }}${{ inputs.key-suffix && format('-{0}', inputs.key-suffix) }}
        restore-keys: |
          ${{ inputs.key-suffix && format('{0}-{1}-{2}-{3}', runner.os, inputs.key, hashFiles('**/Cargo.lock'), inputs.key-suffix) }}
          ${{ runner.os }}-${{ inputs.key }}-${{ hashFiles('**/Cargo.lock') }}
          ${{ runner.os }}-${{ inputs.key }}-
    - if: ${{ inputs.readonly-cache == 'true' }}
      name: Restore Cache
      id: restore-cache
      uses: actions/cache/restore@v4
      with:
        path: |
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-${{ inputs.key }}-${{ hashFiles('**/Cargo.lock') }}${{ inputs.key-suffix && format('-{0}', inputs.key-suffix) }}
        restore-keys: |
          ${{ inputs.key-suffix && format('{0}-{1}-{2}-{3}', runner.os, inputs.key, hashFiles('**/Cargo.lock'), inputs.key-suffix) }}
          ${{ runner.os }}-${{ inputs.key }}-
    - if: ${{ runner.os == 'Linux' }}
      name: Install Linux dependencies
      shell: bash
      run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev