name: Clippy check
run-name: Clippy check - ${{ github.event_name }} - ${{ github.ref }}

on: push

# Make sure CI fails on all warnings, including Clippy lints
env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  clippy_check:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/cache/restore@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - name: Install Problem Matchers
        run: |
          echo "::add-matcher::.github/problem-matchers/clippy-short.json"
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features --message-format=short
